version: '3.4'

services:
  auditor-de-contrato.api:
    image: auditordecontratoapi:dev
    container_name: auditor-de-contrato.api
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "auditor-de-contrato.api"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_auditor-de-contrato.api$
    volumes:
      - C:\Users\afidelis\Source\Repos\auditor-de-contrato\auditor-de-contrato.api:/app
      - C:\Users\afidelis\Source\Repos\auditor-de-contrato:/src
      - C:\Users\afidelis\vsdbg\vs2017u5:/remote_debugger:rw
#$nuget_volume_mapping_auditor-de-contrato.api$
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_auditor-de-contrato.api$ \"/app/bin/Debug/netcoreapp3.1/auditor-de-contrato.api.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true